### ISSUE TITLE
Grey/White rectangles under USD and asset amounts

### ISSUE THREAD

**Issue by mattiaslightstone** [Component-fi/perpetual-lp-tool#174]
**Environment**
Browser: firefox, brave
OS: MacOS 13

**Steps to repro**
1. Enter dev.perpsim.com
2. View the Price range/amount selector in the top right hand corner
3. Optionally change amounts (with no additional affect)

**Expected Behavior**
- Dollar amounts for each asset is displayed in the same style below the asset amount
- No white or dark grey rectangles

**Actual behavior**
- Dollar amount is not visible
- On Firefox grey bars are visible below the amount
- On Brave/Chrome white bars are visible below the amount 

**Screenshot**
Brave/Chrome
![CleanShot 2022-10-05 at 16 20 01@2x](https://user-images.githubusercontent.com/87032785/194182841-9cbac70a-50dd-4b1d-a5ee-ff5f78cc2ace.png)
Firefox
![CleanShot 2022-10-05 at 16 27 35@2x](https://user-images.githubusercontent.com/87032785/194182921-c5cb65ee-507b-4dad-a27d-8c58c0330879.png)

**Comment by nickwang14** [comment]
Issue has been fixed. Some settings have disabled invisible scrollbars, so applying webkits correctly resolved the issue
