### ISSUE TITLE
Full range sets max asset price to $3.40

### ISSUE THREAD

**Issue by mattiaslightstone** [Component-fi/perpetual-lp-tool#177]
**Environment**
Browser: brave
OS: MacOS 13

**Steps to repro**
1. Enter dev.perpsim.com
2. Select Full Range in the top right hand corner of the Price/Amount Card

**Expected Behavior**
- Max should either have a very large number, or an infinity symbol

**Actual behavior**
- Max displays $3.40 no matter what asset is selected
- The liquidity range still correctly shows the right-hand brush far off screen on the right side.

**Screenshot**
<img width="344" alt="CleanShot 2022-10-05 at 16 57 34@2x" src="https://user-images.githubusercontent.com/87032785/194184621-5c9ce067-e41b-449d-a0dd-dde302f56fb2.png">

**Comment by nickwang14** [comment]
We disabled this for the time being
