### ISSUE TITLE
Incorrect metrics when leverage is added 

### ISSUE THREAD

**Issue by ChristianStlouis** [Component-fi/perpetual-lp-tool#187]
## Description
When I have 1x leverage in a market with certain parameters it shows that my expected ROI is going to be negative. Then changing nothing, except increasing leverage, the APR drastically increases. This doesn't make sense because if I'm expected to lose money with 1x leverage while keeping everything constant I should actually lose more capital and lose it faster if I increase leverage.

In fact it seems that most of the metrics are incorrectly calculated when leverage is increased. 

## Expected Behavior
The metrics section should factor properly when leverage is increased. 

If my initial leverage is 1x and I change it to 10x, ROI and APR should still be negative. IL and Max Draw Down should also never be greater than the amount I can lose. When I have only $100 at risk it's not possible for me to suffer IL greater than $100. However, this happens when I increase my leverage. This is worth discussing, but I think max IL should be less than or equal to my account balance.

## Actual Behavior
To give a more clear scenario, I go to the Aave market and put in $100 with +/- 12% range. I'm looking at prediction with time range of 1M.

With 1x leverage my metrics look like below:
ROI = -10.88%
APR = -127.97%
Total Fees = 7.62
Perp Rewards = 2.80
Time In Range = 40.39%
Time Out of Range = 59.61%
Impermanent Loss = 31.02
Max Draw Down(IL) = 31.02

I change nothing except leverage to 10x then the metrics are as follows:

ROI = 963.68%
APR  = 11331.27%
Total Fees = 75.81
Perp Rewards = 27.83
Time In Range = 40.39%
Time Out of Range = 59.61%
Impermanent Loss = -1,720.88
Max Draw Down(IL) = -1,703.47

So we can see that ROI and APR become drastically positive which does not make sense mathematically. Since IL and Max Draw down are immensely higher than my total fees and perp rewards.

Second, the IL and Max Draw Down are greater than the possible amount I can lose. Although I see what's happening, it's scaling to the amount of $ value I have with the leverage increase.

## Possible Fix
Create a rule where IL and Max Draw Down cannot be greater than my $ value at risk. Same with ROI/APR, the most I can lose is 100% of my capital.

Re-visit the ROI/APR metrics in general. I do not think they are being calculated correctly to begin with and certainly go wonky when introducing leverage.

## Steps to Reproduce
To give a more clear scenario, I go to the Aave market and put in $100 with +/- 12% range. I'm looking at prediction with time range of 1M.

1. Go to Aave market
2. Leave range at +/- 12%
3. Enter $100
4. Change metrics to prediction with a time range of 1M

## Your Environment

* Version used:
* Browser Name and version: Brave Version 1.42.97 Chromium: 104.0.5112.102 
* Operating System and version (desktop or mobile): Desktop Mac M1

**Comment by nickwang14** [comment]
Fixed with liquidation indicator, leverage is now no longer a value that the user can toggle directly
